---
- hosts: all
  become: yes
  tasks:
  - name: install packages
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - build-essential
      - python-dev
      - python-pip
      - nginx
      - vim
      - libreadline-dev
      - htop
      - tree
      - nodejs
      - npm
  - name: symlink node to nodejs
    file:
      src: /usr/bin/nodejs
      dest: /usr/bin/node
      state: link
      owner: root
      group: root
  - name: install virtualenv
    pip:
      name: virtualenv
  - name: install uwsgi (system-wide for emperor mode)
    pip:
      name: uwsgi
  - name: create working directory
    file:
      path: /opt/sites
      state: directory
      owner: www-data
      group: www-data
      mode: 0755
      recurse: yes
  - name: clone the git repo
    git:
      repo: 'https://github.com/abconway/emilyjewell.com.git'
      dest: /opt/sites/emilyjewell.com
  - name: setup the django project
    make:
      chdir: /opt/sites/emilyjewell.com
      target: deploy
  - name: configure emilyjewell.com in nginx sites-available
    template:
      src: templates/nginx/emilyjewell.conf
      dest: /etc/nginx/sites-available/emilyjewell.conf
      owner: root
      group: root
      mode: 0644
  - name: symlink emilyjewell.com nginx conf to sites-enabled
    file:
      src: /etc/nginx/sites-available/emilyjewell.conf
      dest: /etc/nginx/sites-enabled/emilyjewell.conf
      state: link
      owner: root
      group: root
  - name: make the uwsgi conf directories
    file:
      path: /etc/uwsgi/sites
      state: directory
      owner: root
      group: root
      mode: 0644
      recurse: yes
  - name: symlink emilyjewell_uwsgi.ini to /etc/uwsgi/sites
    file:
      src: /opt/sites/emilyjewell.com/emilyjewell_uwsgi.ini
      dest: /etc/uwsgi/sites/emilyjewell_uwsgi.ini
      state: link
      owner: root
      group: root
  - name: configure uwsgi systemd unit file
    template:
      src: templates/uwsgi/uwsgi.service
      dest: /etc/systemd/system/uwsgi.service
      owner: root
      group: root
      mode: 0644
  - name: restart uwsgi service
    systemd:
      name: uwsgi
      state: restarted
  - name: restart nginx service
    systemd:
      name: nginx
      state: restarted
  - name: make sure uwsgi starts on boot
    file:
      src: /etc/systemd/system/uwsgi.service
      dest: /etc/systemd/system/multi-user.target.wants/uwsgi.service
      state: link
      owner: root
      group: root
      mode: 0777
  - name: make sure nginx starts on boot
    file:
      src: /lib/systemd/system/nginx.service
      dest: /etc/systemd/system/multi-user.target.wants/nginx.service
      state: link
      owner: root
      group: root
      mode: 0777
